;; evil mode (vim mode)
(require 'evil)
(evil-mode 1)

;; normal
;; from mbriggs/init-keymap

;; key bindings
; based on: http://stackoverflow.com/questions/8483182/evil-mode-best-practice
; (define-key evil-normal-state-map "\C-e" 'evil-end-of-line)
; (define-key evil-insert-state-map "\C-e" 'end-of-line)
; (define-key evil-visual-state-map "\C-e" 'evil-end-of-line)
; (define-key evil-motion-state-map "\C-e" 'evil-end-of-line)
; (define-key evil-normal-state-map "\C-f" 'evil-forward-char)
; (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
; (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
; (define-key evil-normal-state-map "\C-b" 'evil-backward-char)
; (define-key evil-insert-state-map "\C-b" 'evil-backward-char)
; (define-key evil-visual-state-map "\C-b" 'evil-backward-char)
; (define-key evil-normal-state-map "\C-d" 'evil-delete-char)
; (define-key evil-insert-state-map "\C-d" 'evil-delete-char)
; (define-key evil-visual-state-map "\C-d" 'evil-delete-char)
; (define-key evil-normal-state-map "\C-n" 'evil-next-line)
; (define-key evil-insert-state-map "\C-n" 'evil-next-line)
; (define-key evil-visual-state-map "\C-n" 'evil-next-line)
; (define-key evil-normal-state-map "\C-p" 'evil-previous-line)
; (define-key evil-insert-state-map "\C-p" 'evil-previous-line)
; (define-key evil-visual-state-map "\C-p" 'evil-previous-line)
; (define-key evil-normal-state-map "\C-w" 'evil-delete)
; (define-key evil-insert-state-map "\C-w" 'evil-delete)
; (define-key evil-visual-state-map "\C-w" 'evil-delete)
; (define-key evil-normal-state-map "\C-y" 'yank)
; (define-key evil-insert-state-map "\C-y" 'yank)
; (define-key evil-visual-state-map "\C-y" 'yank)
; (define-key evil-normal-state-map "\C-k" 'kill-line)
; (define-key evil-insert-state-map "\C-k" 'kill-line)
; (define-key evil-visual-state-map "\C-k" 'kill-line)
; (define-key evil-normal-state-map "Q" 'call-last-kbd-macro)
; (define-key evil-visual-state-map "Q" 'call-last-kbd-macro)
; (define-key evil-normal-state-map (kbd "TAB") 'evil-undefine)

; (defun evil-undefine ()
;  (interactive)
;  (let (evil-mode-map-alist)
;    (call-interactively (key-binding (this-command-keys)))))

; (define-key evil-normal-state-map (kbd "DEL") (lambda ()
;                     (interactive)
;                     (previous-line 10)
;                     (evil-scroll-line-up 10)
;                     ))

; (define-key evil-normal-state-map (kbd "=") (lambda ()
;                       (interactive)
;                       (next-line 10)
;                       (evil-scroll-line-down 10)
;                       ))
